config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'

  resources :subs
  resources :posts do
    resources :comments, only: :new
  end

  resources :users
  resource :session


  resources :comments, only: [:create, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id                :integer          not null, primary key
#  content           :text             not null
#  user_id           :integer          not null
#  post_id           :integer          not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  parent_comment_id :integer
#

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :content, presence: true
  
  has_many :child_comments,
    foreign_key: :parent_comment_id,
    class_name: 'Comment'

  belongs_to :parent_comment,
    foreign_key: :parent_comment_id,
    class_name: 'Comment',
    optional: true



end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :subs, presence: true
  belongs_to :author,
  foreign_key: :user_id,
  class_name: 'User'

  # belongs_to :sub_forum,
  # foreign_key: :sub_id,
  # class_name: 'Sub',

  has_many :post_subs

  has_many :subs,
  through: :post_subs,
  source: :sub

  has_many :comments
end

app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  sub_id     :integer          not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord
  validates :sub, :post, presence: true
  belongs_to :sub
  belongs_to :post


end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  belongs_to :moderator,
  foreign_key: :moderator_id,
  class_name: 'User'

  has_many :post_subs

  has_many :posts,
  through: :post_subs,
  source: :post

  validates :title, :moderator, presence: true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :moderated_subs,
  foreign_key: :moderator_id,
  class_name: 'Sub'

  has_many :authored_posts,
  foreign_key: :user_id,
  class_name: 'Post'

  has_many :comments

  after_initialize :ensure_session_token
  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    session[:session_token] = user.reset_session_token
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def is_moderator?
    current_user.moderated_subs.include?(Sub.find(params[:id]))
  end

  def ensure_moderator
    redirect_to subs_url unless is_moderator?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def show
    @comment = Comment.find(params[:id])
    @parent_comment_children = @comment.child_comments
  end

  def comment_params
    params.require(:comment).permit(:content, :post_id, :parent_comment_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :ensure_logged_in

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      render :show
    else
      flash.now[:error] = @post.errors.full_messages
      render :new
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = current_user.authored_posts.find(params[:id])
    if @post.update(post_params)
      render :show
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    @all_comments = Comment.all
    @parent_comments = @post.comments.where(parent_comment_id: nil)
    @third_guy = @all_comments - @parent_comments

  end


  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub_forum)
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ["Invalid login"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :ensure_moderator, only: [:update, :destroy, :edit]
  before_action :ensure_logged_in, only: [:create, :update, :destroy]
  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
    @sub = Sub.find(params[:id])
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def new
    @sub = Sub.new
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def edit
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper


end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p><a href="/comments/<%= comment.id %>"> <%= comment.content %></a></p>
<% return comment if comment.child_comments.nil? %>
  <% comment.child_comments.each do |child| %>
  <ul>
    <li>  <%= render 'comments/comment', comment: child %>   </li>
  </ul>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<form class="" action="/comments" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[post_id]" value="<%= params[:post_id] %>">

  <label>Content
    <input type="text" name="comment[content]" value="">
  </label>

  <input type="submit" name="" value="Comment">

</form>

app/views/comments/show.html.erb
<h2> <%= @comment.content %> </h2>

<h1>New Comment</h1>

<form class="" action="/comments" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[post_id]" value="<%= @comment.post_id %>">
  <input type="hidden" name="comment[parent_comment_id]" value="<%= params[:id] %>">

  <label>Content
    <input type="text" name="comment[content]" value="">
  </label>

  <input type="submit" name="" value="Comment">

</form>


<% @parent_comment_children.each do |child| %>
  <a href="/comments/<%= child.id %>"><%= child.content %></a>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h4><a href="/subs">Homepage</a></h4>
    <%= flash[:errors] %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<form class="" action="/posts/<%= @post.id %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PATCH">

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>
  <br>
  <label>Forums:
    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |s| %>
    <li><%= s.title %>
      <input <%= @post.sub_ids.include?(s.id) ? 'checked' : '' %> type="checkbox" name="post[sub_ids][]" value="<%= s.id %>">
    </li>
    <% end %>
  </label>

  <input type="submit" name="" value="Edit Post">

</form>

app/views/posts/new.html.erb
<h2>Make A New Post Here</h2>

<form class="" action="/posts" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">


  <label>Title
    <input type="text" name="post[title]" value="">
  </label>

  <label>Content
    <input type="text" name="post[content]" value="">
  </label>
  <br>
  <label>Forums:
    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |s| %>
    <li><%= s.title %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= s.id %>">
    </li>
    <% end %>
  </label>

  <input type="submit" name="" value="Make A Post">

</form>

app/views/posts/show.html.erb
<h1>  <%= @post.title %>  </h1>
<p> <%= @post.content %>   </p>

<h2>Posted To:</h2>

<ul>
  <% @post.subs.each do |s| %>
    <li><%= s.title %></li>
  <% end %>
</ul>

<a href="/posts/<%= @post.id %>/edit">Edit Post</a>

<a href="<%= new_post_comment_url(@post) %>">New Comment</a>
<% @all_comments.each do |top_comment| %>
  <% if top_comment.parent_comment_id.nil? %>
    <p><a href="/comments/<%= top_comment.id %>"> <%= top_comment.content %></a></p>
    <ul>
      <% top_comment.child_comments.each do |comment|%>
      <%= render 'comments/comment', comment: comment %>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

app/views/subs/index.html.erb
<h1>Sub Forums:</h1>
<% @subs.each do |s| %>

<h2>  <a href="/subs/<%= s.id %>"><%= s.title %></a></h2>
<p> <%= s.description %> </p>
<h3><%= s.moderator.username %></h3>
<% end %>

app/views/subs/new.html.erb
<h1>Create Sub Forum</h1>

<form class="" action="/subs" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Title
    <input type="text" name="sub[title]" value="">
  </label>

  <label>Description
    <input type="text" name="sub[description]" value="">
  </label>

  <input type="submit" name="" value="Create Sub Forum">

</form>

app/views/subs/show.html.erb
<h1>  <%= @sub.title %> </h1>
<p> <%= @sub.description %>  </p>

<h3> Moderated By : <%= @sub.moderator.username %> </h3>
<h2>Posts:</h2>
  <% @sub.posts.each do |post| %>
    <a href="/posts/<%= post.id %>"><p>  <%= post.title %>  </p></a>
    <p>  <%= post.content %>  </p>
    <p>  <%= post.author.username %>  </p>
  <% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form class="" action="/users" method="post">

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Create Account">

</form>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>